# This file is part of the CampaignChain package.
#
# (c) Sandro Groganz <sandro@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    campaignchain.job.campaign.repeating:
        class: CampaignChain\Campaign\RepeatingBundle\Job\JobAction
        arguments: [ @doctrine.orm.entity_manager, @service_container ]
    campaignchain.campaign.repeating:
        class: CampaignChain\Campaign\RepeatingBundle\EntityService\RepeatingCampaignService
        arguments: [ @doctrine.orm.entity_manager, @service_container ]