# This file is part of the CampaignChain package.
#
# (c) CampaignChain, Inc. <info@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    campaignchain.job.campaign.repeating:
        class: CampaignChain\Campaign\RepeatingBundle\Service\Job
        arguments: [ @doctrine.orm.entity_manager, @service_container ]
    campaignchain.campaign.repeating.copy:
        class: CampaignChain\Campaign\RepeatingBundle\Service\Copy
        arguments: [ @doctrine.orm.entity_manager, @service_container ]